---
rounds_idx: 1
reference_date_col_name: 'reference_date'
target_date_col_name: 'target_end_date'
horizon_col_name: 'horizon'
initial_checked_models: [ 'epiENGAGE-ensemble_mean' ]
initial_xaxis_range:
  - '2025-08-01'
  - '2026-07-01'
task_id_text:
  location: # location,location_name
    "denver": "Denver, CO"
    "mesa": "Mesa, CO"
    "colorado-springs": "Colorado Springs, CO"
    "weld": "Weld, CO"
    "boulder": "Boulder, CO"
    "larimer": "Larimer, CO"
    "colorado": "Colorado"
    "savannah": "Savannah, GA"
    "floyd": "Floyd, GA"
    "hall": "Hall, GA"
    "marietta": "Marietta, GA"
    "macon": "Macon, GA"
    "henry": "Henry, GA"
    "cherokee": "Cherokee, GA"
    "athens": "Athens, GA"
    "south-augusta": "South Augusta, GA"
    "columbus": "Columbus, GA"
    "la-grange": "La Grange, GA"
    "georgia": "Georgia"
    "indianapolis": "Indianapolis, IN"
    "indiana": "Indiana"
    "bangor": "Bangor, ME"
    "portland": "Portland, ME"
    "maine": "Maine"
    "baltimore": "Baltimore, MD"
    "frederick": "Frederick, MD"
    "montgomery": "Montgomery, MD"
    "harford": "Harford, MD"
    "maryland": "Maryland"
    "worcester": "Worcester, MA"
    "pittsfield": "Pittsfield, MA"
    "boston": "Boston, MA"
    "springfield": "Springfield, MA"
    "new-bedford": "New Bedford, MA"
    "lynn": "Lynn, MA"
    "massachusetts": "Massachusetts"
    "st-paul": "St. Paul, MN"
    "duluth": "Duluth, MN"
    "minneapolis": "Minneapolis, MN"
    "st-cloud": "St. Cloud, MN"
    "rochester": "Rochester, MN"
    "minnesota": "Minnesota"
    "columbia": "Columbia, SC"
    "greenville": "Greenville, SC"
    "florence": "Florence, SC"
    "charleston": "Charleston, SC"
    "rock-hill": "Rock Hill, SC"
    "horry": "Horry, SC"
    "south-carolina": "South Carolina"
    "houston": "Houston, TX"
    "san-antonio": "San Antonio, TX"
    "beaumont": "Beaumont, TX"
    "el-paso": "El Paso, TX"
    "austin": "Austin, TX"
    "dallas": "Dallas, TX"
    "texas": "Texas"
    "provo": "Provo, UT"
    "salt-lake-city": "Salt Lake City, UT"
    "ogden": "Ogden, UT"
    "utah": "Utah"
    "roanoke": "Roanoke, VA"
    "virginia": "Virginia"
    "nyc": "NYC"
    "nenc": "Northeastern, NC"
    "senc": "Southeastern, NC"
    "fay-area": "Fayetteville Area, NC"
    "rtp-area": "Research Triangle Park Area, NC"
    "triad-area": "Triad Area, NC"
    "wnc": "Western, NC"
    "clt-area": "Charolette Area, NC"
    "north-carolina": "North Carolina"

#target_data_file_name:  # this hub uses the default time-series target data: "target-data/time-series.csv"
disclaimer: 'Observed counts are aggregated by week and predictions are made for each week. Dates associated with specific data points reflect the last day (Saturday) of the week.'
